#!/usr/bin/env bash
#
# install-llvm.sh — install the exact LLVM build the LLVM backend needs.
#
# Wasmer's LLVM backend links LLVM *statically* (inkwell feature
# `llvm<MAJOR>-<MINOR>-prefer-static`), so it needs a matching static build —
# not a stock distro package. This installs the same prebuilt LLVM that
# Wasmer CI uses (https://github.com/wasmerio/llvm-custom-builds), wires up
# the `LLVM_SYS_<ver>_PREFIX` env var, and writes a sourceable env file.
#
# The required version is auto-detected from lib/compiler-llvm/Cargo.toml, so
# this script keeps working after a version bump and on any box.
#
# Usage:
#   scripts/install-llvm.sh [--prefix DIR] [--version MAJOR] [--force] [--print-env]
#
# Options:
#   --prefix DIR    Install location (default: <repo>/.llvm, or $LLVM_DIR).
#   --version N     Override the LLVM major version (default: auto-detected).
#   --force         Re-download even if an install is already present.
#   --print-env     Only print the env exports for an existing install, then exit.
#   -h, --help      Show this help.
#
# After running, either `source <repo>/.llvm-env.sh` or follow the printed
# instructions, then:  cargo build --release --features llvm
#
# Env overrides:
#   LLVM_DIR                  install prefix
#   LLVM_CUSTOM_BUILDS_BASE   release base URL (default: wasmerio/llvm-custom-builds)

set -euo pipefail

# --- locate repo root (works from anywhere) ---------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BASE_URL="${LLVM_CUSTOM_BUILDS_BASE:-https://github.com/wasmerio/llvm-custom-builds/releases/download}"
FORCE=0
PRINT_ENV_ONLY=0
VERSION_OVERRIDE=""
PREFIX="${LLVM_DIR:-${REPO_ROOT}/.llvm}"

die() { echo "error: $*" >&2; exit 1; }
log() { echo ">> $*" >&2; }

while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --version) VERSION_OVERRIDE="$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --print-env) PRINT_ENV_ONLY=1; shift ;;
    -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
done

# --- detect required LLVM version from the repo -----------------------------
# inkwell feature looks like: "llvm22-1-prefer-static"  ->  major=22 minor=1
detect_feature() {
  grep -oE 'llvm[0-9]+-[0-9]+-prefer-static' \
    "${REPO_ROOT}/lib/compiler-llvm/Cargo.toml" 2>/dev/null | head -1
}

if [ -n "${VERSION_OVERRIDE}" ]; then
  MAJOR="${VERSION_OVERRIDE}"
  # llvm-sys minor is needed for the env var; read it from the feature if we can
  MINOR="$(detect_feature | sed -nE 's/^llvm[0-9]+-([0-9]+).*/\1/p')"
  MINOR="${MINOR:-1}"
else
  FEATURE="$(detect_feature)"
  [ -n "${FEATURE}" ] || die "could not detect LLVM version from lib/compiler-llvm/Cargo.toml; pass --version N"
  MAJOR="$(printf '%s' "${FEATURE}" | sed -nE 's/^llvm([0-9]+)-[0-9]+.*/\1/p')"
  MINOR="$(printf '%s' "${FEATURE}" | sed -nE 's/^llvm[0-9]+-([0-9]+).*/\1/p')"
fi
[ -n "${MAJOR}" ] && [ -n "${MINOR}" ] || die "failed to parse LLVM major/minor"

# llvm-sys env var follows the crate's major version (LLVM 22.1 -> 221).
SYS_VER="${MAJOR}${MINOR}"
ENV_VAR="LLVM_SYS_${SYS_VER}_PREFIX"

# --- env-printing helper ----------------------------------------------------
print_env() {
  local dir="$1"
  echo "export ${ENV_VAR}=\"${dir}\""
  echo "export PATH=\"${dir}/bin:${dir}/usr/bin:\$PATH\""
}

write_env_file() {
  local dir="$1"
  local env_file="${REPO_ROOT}/.llvm-env.sh"
  {
    echo "# generated by scripts/install-llvm.sh — source this before building with --features llvm"
    print_env "$dir"
  } > "${env_file}"
  log "wrote ${env_file}"
  # In CI, also export to the job environment.
  if [ -n "${GITHUB_ENV:-}" ]; then
    echo "${ENV_VAR}=${dir}" >> "${GITHUB_ENV}"
  fi
  if [ -n "${GITHUB_PATH:-}" ]; then
    echo "${dir}/bin"     >> "${GITHUB_PATH}"
    echo "${dir}/usr/bin" >> "${GITHUB_PATH}"
  fi
}

# --- already installed? -----------------------------------------------------
installed_major() {
  local cfg="${PREFIX}/bin/llvm-config"
  [ -x "${cfg}" ] || cfg="${PREFIX}/usr/bin/llvm-config"
  [ -x "${cfg}" ] || return 1
  "${cfg}" --version 2>/dev/null | cut -d. -f1
}

if [ "${PRINT_ENV_ONLY}" = 1 ]; then
  [ "$(installed_major || true)" = "${MAJOR}" ] || die "no LLVM ${MAJOR} install at ${PREFIX}"
  print_env "${PREFIX}"
  exit 0
fi

if [ "${FORCE}" = 0 ] && [ "$(installed_major || true)" = "${MAJOR}" ]; then
  log "LLVM ${MAJOR} already installed at ${PREFIX} (use --force to reinstall)"
  write_env_file "${PREFIX}"
  echo; print_env "${PREFIX}"
  exit 0
fi

# --- pick the prebuilt asset for this OS/arch -------------------------------
OS="$(uname -s)"; ARCH="$(uname -m)"
case "${OS}" in
  Linux)  os_tag="linux" ;;
  Darwin) os_tag="darwin" ;;
  MINGW*|MSYS*|CYGWIN*|Windows_NT) os_tag="windows" ;;
  *) die "unsupported OS: ${OS}" ;;
esac
case "${ARCH}" in
  x86_64|amd64) arch_tag="amd64" ;;
  aarch64|arm64) arch_tag="aarch64" ;;
  *) die "unsupported arch: ${ARCH}" ;;
esac
# wasmerio/llvm-custom-builds provides: linux-{amd64,aarch64}, darwin-aarch64, windows-amd64
ASSET="llvm-${os_tag}-${arch_tag}.tar.xz"
URL="${BASE_URL}/${MAJOR}.x/${ASSET}"

# --- download + extract -----------------------------------------------------
have() { command -v "$1" >/dev/null 2>&1; }
have tar || die "tar is required"
have xz  || log "note: 'xz' not found; relying on tar's xz support"

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT
TARBALL="${TMP}/llvm.tar.xz"

# GitHub release asset downloads work unauthenticated; a token (if present)
# avoids rate limits.
AUTH=()
[ -n "${GITHUB_TOKEN:-}" ] && AUTH=(-H "Authorization: Bearer ${GITHUB_TOKEN}")

log "downloading LLVM ${MAJOR}.${MINOR} for ${os_tag}-${arch_tag}"
log "  ${URL}"
if have curl; then
  curl "${AUTH[@]}" --retry 3 --proto '=https' --tlsv1.2 -sSfL "${URL}" -o "${TARBALL}" \
    || die "download failed (no ${ASSET} for ${MAJOR}.x?): ${URL}"
elif have wget; then
  wget -q "${URL}" -O "${TARBALL}" || die "download failed: ${URL}"
else
  die "need curl or wget"
fi

log "extracting to ${PREFIX}"
rm -rf "${PREFIX}"
mkdir -p "${PREFIX}"
tar xf "${TARBALL}" --strip-components=1 -C "${PREFIX}"

# --- verify -----------------------------------------------------------------
got="$(installed_major || true)"
[ "${got}" = "${MAJOR}" ] || die "installed LLVM reports major '${got}', expected '${MAJOR}'"
CFG="${PREFIX}/bin/llvm-config"; [ -x "${CFG}" ] || CFG="${PREFIX}/usr/bin/llvm-config"
log "installed: $("${CFG}" --version) at $("${CFG}" --prefix)"

write_env_file "${PREFIX}"

cat >&2 <<EOF

LLVM ${MAJOR} ready. To build the LLVM backend in this shell:

  source ${REPO_ROOT}/.llvm-env.sh
  cargo build --release --features llvm

Or set the var inline:

EOF
print_env "${PREFIX}"
